apiVersion: v1
kind: Service
metadata:
  name: sandbox-simpleapp-svc
  namespace: default
spec:
  selector:
    app: sandbox-simple-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP