kind: ConfigMap
apiVersion: v1
metadata:
  name: simpleapp-config
  namespace: default
data:
  property.from.configmaps.application.properties: This property was set via configmap
  spring.datasource.url: property from configmap - spring.datasource.url
